# Generated by Django 4.2.28 on 2026-06-07 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_diagnosis_encrypted', models.TextField(blank=True, db_column='diagnosis')),
                ('_treatment_plan_encrypted', models.TextField(blank=True, db_column='treatment_plan')),
                ('_notes_encrypted', models.TextField(blank=True, db_column='notes')),
                ('_allergies_encrypted', models.TextField(blank=True, db_column='allergies')),
                ('record_date', models.DateTimeField(auto_now_add=True)),
                ('record_type', models.CharField(choices=[('opd', 'OPD Record'), ('ipd', 'IPD Record'), ('emergency', 'Emergency'), ('follow_up', 'Follow Up')], default='opd', max_length=20)),
                ('lab_tests', models.JSONField(blank=True, default=list)),
                ('radiology_reports', models.JSONField(blank=True, default=list)),
                ('attachments', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'clinical_records_clinicalrecord',
                'ordering': ['-record_date'],
            },
        ),
        migrations.CreateModel(
            name='RadiologyReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('study_type', models.CharField(max_length=50)),
                ('body_part', models.CharField(max_length=50)),
                ('findings', models.TextField()),
                ('impression', models.TextField()),
                ('images', models.JSONField(blank=True, default=list)),
                ('dicom_study_uid', models.CharField(blank=True, max_length=64)),
                ('clinical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_records', to='clinical_records.clinicalrecord')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('radiologist', models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiology_reports', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clinical_records_radiologyreport',
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=100)),
                ('loinc_code', models.CharField(blank=True, help_text='LOINC code for interoperability', max_length=20)),
                ('result_value', models.CharField(max_length=255)),
                ('reference_range', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('result_file', models.FileField(blank=True, help_text='Scanned lab report or image', upload_to='lab_results/%Y/%m/')),
                ('clinical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='clinical_records.clinicalrecord')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(limit_choices_to={'role': 'lab_tech'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clinical_records_labresult',
                'ordering': ['-created_at'],
            },
        ),
    ]
