# Generated by Django 4.2.28 on 2026-06-07 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinical_records', '0001_initial'),
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalrecord',
            name='consultation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_record', to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_records', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='clinicalrecord',
            index=models.Index(fields=['patient', 'record_date'], name='clinical_re_patient_69cfce_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalrecord',
            index=models.Index(fields=['record_type', 'record_date'], name='clinical_re_record__c8d18d_idx'),
        ),
    ]
