# Generated by Django 4.2.28 on 2026-06-07 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('nida_nin', models.CharField(blank=True, db_index=True, help_text='20-digit National Identification Number', max_length=20, null=True, verbose_name='NIDA NIN')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='phone number')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist'), ('receptionist', 'Receptionist'), ('lab_tech', 'Laboratory Technician'), ('accountant', 'Accountant'), ('ward_clerk', 'Ward Clerk')], default='receptionist', max_length=20, verbose_name='role')),
                ('professional_reg_no', models.CharField(blank=True, help_text='Medical Council or Nursing Council registration number', max_length=50, verbose_name='professional registration number')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('failed_login_attempts', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('mfa_secret', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'accounts_user',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(choices=[('national_referral', 'National Referral Hospital'), ('regional_referral', 'Regional Referral Hospital'), ('district_hospital', 'District Hospital'), ('health_center', 'Health Center'), ('dispensary', 'Dispensary'), ('clinic', 'Clinic')], max_length=20)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('region', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('ward', models.CharField(max_length=50)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('nhif_facility_code', models.CharField(blank=True, db_index=True, max_length=20)),
                ('tra_tin', models.CharField(blank=True, max_length=20, verbose_name='TRA TIN')),
                ('vfd_serial_number', models.CharField(blank=True, max_length=50)),
                ('dhis2_org_unit_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'facilities',
                'db_table': 'accounts_facility',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('head', models.OneToOneField(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_department', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_department',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='accounts.facility'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='accounts_us_role_2b136f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['facility', 'department'], name='accounts_us_facilit_14fee0_idx'),
        ),
    ]
