# Generated by Django 4.2.28 on 2026-06-07 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DHIS2DataElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dhis2_uid', models.CharField(db_index=True, max_length=11, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('category_combo', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('mtuha_book', models.CharField(blank=True, choices=[('book_3', 'Book 3 - OPD'), ('book_5', 'Book 5 - RCH'), ('book_6', 'Book 6 - Immunization'), ('book_10', 'Book 10 - Hospital Report')], max_length=20)),
                ('mtuha_indicator', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'reporting_dhis2_data_element',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MTUHAIndicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('indicator_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('book', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=50)),
                ('data_source', models.CharField(help_text='Django model.field reference', max_length=100)),
                ('aggregation_method', models.CharField(choices=[('count', 'Count'), ('sum', 'Sum'), ('avg', 'Average')], max_length=20)),
            ],
            options={
                'db_table': 'reporting_mtuha_indicator',
                'ordering': ['indicator_code'],
            },
        ),
        migrations.CreateModel(
            name='DHIS2Report',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_period', models.CharField(help_text='YYYYMM format', max_length=10)),
                ('report_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=20)),
                ('data_values', models.JSONField(default=dict, help_text='DHIS2 data value set')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('acknowledged', 'Acknowledged'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('dhis2_response', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dhis2_reports', to='accounts.facility')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reporting_dhis2_report',
                'ordering': ['-report_period'],
                'unique_together': {('report_period', 'facility', 'report_type')},
            },
        ),
    ]
