# Generated by Django 4.2.28 on 2026-06-07 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('nhif', 'NHIF'), ('insurance', 'Other Insurance'), ('card', 'Card Payment'), ('mobile_money', 'Mobile Money'), ('mixed', 'Mixed Payment')], default='cash', max_length=20)),
                ('vfd_registered', models.BooleanField(default=False)),
                ('vfd_gc', models.PositiveIntegerField(blank=True, null=True, verbose_name='VFD Global Counter')),
                ('vfd_rctnum', models.PositiveIntegerField(blank=True, null=True, verbose_name='VFD Receipt Number')),
                ('vfd_znum', models.CharField(blank=True, max_length=8, verbose_name='VFD Z-Report Number')),
                ('vfd_signature', models.TextField(blank=True)),
                ('vfd_qr_code', models.TextField(blank=True)),
                ('vfd_registered_at', models.DateTimeField(blank=True, null=True)),
                ('nhif_authorized', models.BooleanField(default=False)),
                ('nhif_authorization_id', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'billing_invoice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VFDCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_counter', models.PositiveIntegerField(default=0, help_text='GC: Never resets')),
                ('daily_counter', models.PositiveIntegerField(default=0, help_text='DC: Resets at midnight')),
                ('z_report_number', models.CharField(blank=True, max_length=8)),
                ('last_z_report_date', models.DateField(blank=True, null=True)),
                ('last_receipt_date', models.DateTimeField(blank=True, null=True)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vfd_counter', to='accounts.facility')),
            ],
            options={
                'db_table': 'billing_vfd_counter',
            },
        ),
        migrations.CreateModel(
            name='NHIFClaim',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('member_card_number', models.CharField(max_length=20)),
                ('authorization_id', models.CharField(blank=True, max_length=50)),
                ('scheme_code', models.CharField(blank=True, max_length=20)),
                ('claim_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('diagnosis_codes', models.JSONField(default=list, help_text='ICD-10 codes for claim')),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('acknowledged', 'Acknowledged'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('nhif_reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('submission_payload', models.JSONField(default=dict)),
                ('api_response', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nhif_claims', to='accounts.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nhif_claims', to='patients.patient')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_nhif_claims', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_nhif_claim',
                'ordering': ['-claim_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('item_code', models.CharField(blank=True, help_text='NHIF/MSD item code', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('consultation', 'Consultation'), ('procedure', 'Procedure'), ('medication', 'Medication'), ('laboratory', 'Laboratory'), ('radiology', 'Radiology'), ('ward', 'Ward Charges'), ('other', 'Other')], max_length=20)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice')),
            ],
            options={
                'db_table': 'billing_invoice_item',
            },
        ),
    ]
