# Generated by Django 4.2.28 on 2026-06-07 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('admitted', 'Admitted'), ('discharged', 'Discharged'), ('transferred', 'Transferred'), ('absconded', 'Absconded'), ('deceased', 'Deceased')], default='admitted', max_length=20)),
                ('admitting_diagnosis', models.TextField()),
                ('discharge_diagnosis', models.TextField(blank=True)),
                ('discharge_summary', models.TextField(blank=True)),
                ('discharge_disposition', models.CharField(blank=True, choices=[('home', 'Home'), ('transfer', 'Transfer'), ('referral', 'Referral'), ('died', 'Died'), ('ama', 'Against Medical Advice')], max_length=20)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_bill', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('review_due', models.DateTimeField(blank=True, null=True)),
                ('review_overdue', models.BooleanField(default=False)),
                ('admitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wards_admission',
                'ordering': ['-admission_date'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('ward_type', models.CharField(choices=[('general_male', 'General Male'), ('general_female', 'General Female'), ('maternity', 'Maternity'), ('pediatric', 'Pediatric'), ('surgical', 'Surgical'), ('icu', 'Intensive Care'), ('nicu', 'Neonatal ICU'), ('isolation', 'Isolation'), ('private', 'Private')], max_length=20)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('capacity', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='accounts.facility')),
            ],
            options={
                'db_table': 'wards_ward',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NursingNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('vital_temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('vital_blood_pressure', models.CharField(blank=True, max_length=20)),
                ('vital_pulse', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vital_respiration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vital_spo2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_notes', to='wards.admission')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(limit_choices_to={'role': 'nurse'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nursing_notes', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wards_nursing_note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationAdministrationRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_time', models.DateTimeField()),
                ('administered_time', models.DateTimeField(blank=True, null=True)),
                ('dose_given', models.CharField(max_length=50)),
                ('route', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('missed', models.BooleanField(default=False)),
                ('missed_reason', models.TextField(blank=True)),
                ('administered_by', models.ForeignKey(limit_choices_to={'role__in': ['nurse', 'doctor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_medications', to=settings.AUTH_USER_MODEL)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mar_entries', to='wards.admission')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mar_entries', to='consultations.prescription')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medication Administration Record',
                'verbose_name_plural': 'Medication Administration Records',
                'db_table': 'wards_mar',
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bed_number', models.CharField(max_length=10)),
                ('bed_type', models.CharField(choices=[('standard', 'Standard'), ('electric', 'Electric'), ('cot', 'Cot'), ('bassinet', 'Bassinet'), ('isolation', 'Isolation')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Maintenance'), ('cleaning', 'Cleaning')], default='available', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='wards.ward')),
            ],
            options={
                'db_table': 'wards_bed',
            },
        ),
        migrations.AddField(
            model_name='admission',
            name='bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='wards.bed'),
        ),
        migrations.AddField(
            model_name='admission',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admission',
            name='discharged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharged_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admission',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='accounts.facility'),
        ),
        migrations.AddField(
            model_name='admission',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='admission',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admission',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='wards.ward'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['ward', 'status'], name='wards_bed_ward_id_5cd9b8_idx'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['status', 'is_active'], name='wards_bed_status_6f393b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('ward', 'bed_number')},
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['patient', 'status'], name='wards_admis_patient_79a8b5_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['ward', 'status'], name='wards_admis_ward_id_5e8b8a_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['admission_date', 'discharge_date'], name='wards_admis_admissi_98b5a5_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['review_due', 'review_overdue'], name='wards_admis_review__254c3e_idx'),
        ),
    ]
