# Generated by Django 4.2.28 on 2026-06-07 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_date', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('checked_in', 'Checked In'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='routine', max_length=20)),
                ('visit_type', models.CharField(choices=[('new', 'New Case'), ('follow_up', 'Follow Up'), ('referral', 'Referral'), ('emergency', 'Emergency')], default='new', max_length=20)),
                ('vital_temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('vital_blood_pressure_sys', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vital_blood_pressure_dia', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vital_heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vital_respiratory_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vital_oxygen_saturation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vital_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vital_height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vital_bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('chief_complaint', models.TextField()),
                ('history_of_present_illness', models.TextField(blank=True)),
                ('physical_examination', models.TextField(blank=True)),
                ('assessment_and_plan', models.TextField(blank=True)),
                ('disposition', models.CharField(blank=True, choices=[('discharged', 'Discharged'), ('admitted', 'Admitted'), ('referred', 'Referred'), ('died', 'Died'), ('absconded', 'Absconded')], max_length=20)),
                ('referral_facility', models.CharField(blank=True, max_length=255)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_nhif_claimable', models.BooleanField(default=False)),
                ('is_notifiable_disease', models.BooleanField(default=False, help_text='Flag for e-IDSR / DHIS2 outbreak reporting')),
            ],
            options={
                'db_table': 'consultations_consultation',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='ICD10Code',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(db_index=True, max_length=10)),
                ('subcategory', models.CharField(blank=True, max_length=50)),
                ('is_sdh', models.BooleanField(default=False, help_text='Social Determinants of Health Z-code (Z55-Z65)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ICD-10-CM Code',
                'verbose_name_plural': 'ICD-10-CM Codes',
                'db_table': 'consultations_icd10_code',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=50)),
                ('duration_days', models.PositiveSmallIntegerField()),
                ('quantity_prescribed', models.PositiveIntegerField()),
                ('instructions', models.TextField(blank=True)),
                ('dispensed', models.BooleanField(default=False)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='consultations.consultation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dispensed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'pharmacist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consultations_prescription',
                'ordering': ['-created_at'],
            },
        ),
    ]
