# Generated by Django 4.2.28 on 2026-06-07 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultations', '0001_initial'),
        ('patients', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultation',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='accounts.facility'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='primary_diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_consultations', to='consultations.icd10code'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='sdoh_codes',
            field=models.ManyToManyField(blank=True, help_text='Social Determinants of Health Z-codes (Z55-Z65)', limit_choices_to={'is_sdh': True}, related_name='sdoh_consultations', to='consultations.icd10code'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='secondary_diagnoses',
            field=models.ManyToManyField(blank=True, related_name='secondary_consultations', to='consultations.icd10code'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['patient', 'visit_date'], name='consultatio_patient_6176d3_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['doctor', 'visit_date'], name='consultatio_doctor__510fe7_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['facility', 'visit_date', 'status'], name='consultatio_facilit_1dd8ba_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['is_notifiable_disease', 'visit_date'], name='consultatio_is_noti_7bf15b_idx'),
        ),
    ]
