# Generated by Django 4.2.28 on 2026-06-07 21:10

import apps.patients.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nida_nin', models.CharField(blank=True, db_index=True, help_text='20-digit National Identification Number from NIDA', max_length=20, null=True, unique=True, validators=[apps.patients.validators.validate_nida_nin], verbose_name='NIDA NIN')),
                ('biometric_verified', models.BooleanField(default=False)),
                ('biometric_reference', models.CharField(blank=True, help_text='Reference ID from NIDA biometric system', max_length=255)),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='middle name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('date_of_birth', models.DateField(help_text='Validated against NIDA records', validators=[apps.patients.validators.validate_no_future_date])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], help_text='Required for HIE and MTUHA reporting', max_length=10)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('separated', 'Separated')], max_length=10)),
                ('phone_number', models.CharField(max_length=15, verbose_name='phone number')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('region', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('ward', models.CharField(max_length=50)),
                ('village_street', models.CharField(blank=True, max_length=100)),
                ('nhif_card_number', models.CharField(blank=True, db_index=True, help_text='NHIF membership card number', max_length=20)),
                ('insurance_scheme', models.CharField(blank=True, max_length=50)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('education_level', models.CharField(blank=True, max_length=50)),
                ('consent_status', models.BooleanField(default=False, help_text='Explicit consent for processing sensitive health data per PDPA 2022 Section 5')),
                ('consent_date', models.DateTimeField(blank=True, null=True)),
                ('consent_method', models.CharField(blank=True, choices=[('written', 'Written Signature'), ('digital', 'Digital Consent'), ('verbal', 'Verbal (Witnessed)'), ('guardian', 'Guardian Consent')], max_length=20)),
                ('consent_withdrawn', models.BooleanField(default=False)),
                ('consent_withdrawn_date', models.DateTimeField(blank=True, null=True)),
                ('patient_number', models.CharField(db_index=True, help_text='Internal facility patient number (MRN)', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deceased', models.BooleanField(default=False)),
                ('deceased_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='accounts.facility')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'patient',
                'verbose_name_plural': 'patients',
                'db_table': 'patients_patient',
                'permissions': [('export_patient_data', 'Can export patient data for reporting'), ('view_phi', 'Can view protected health information')],
            },
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('relationship', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'next of kin',
                'db_table': 'patients_next_of_kin',
            },
        ),
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('granted', 'Consent Granted'), ('withdrawn', 'Consent Withdrawn'), ('updated', 'Consent Updated')], max_length=20)),
                ('method', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_logs', to='patients.patient')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patients_consent_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['nida_nin', 'is_active'], name='patients_pa_nida_ni_4ea139_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['patient_number', 'facility'], name='patients_pa_patient_303931_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['nhif_card_number', 'insurance_expiry'], name='patients_pa_nhif_ca_d2896f_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['last_name', 'first_name', 'date_of_birth'], name='patients_pa_last_na_2cbb9f_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['region', 'district', 'ward'], name='patients_pa_region_1f7a19_idx'),
        ),
    ]
