# Generated by Django 4.2.28 on 2026-06-07 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExportLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_type', models.CharField(max_length=50)),
                ('filters_applied', models.JSONField(default=dict)),
                ('record_count', models.PositiveIntegerField()),
                ('file_format', models.CharField(max_length=20)),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('download_url', models.URLField(blank=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_export_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('EXPORT', 'Export'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('FAILED_LOGIN', 'Failed Login'), ('CONSENT_GRANTED', 'Consent Granted'), ('CONSENT_WITHDRAWN', 'Consent Withdrawn'), ('PRESCRIPTION_DISPENSED', 'Prescription Dispensed'), ('CLAIM_SUBMITTED', 'Claim Submitted'), ('VFD_RECEIPT', 'VFD Receipt Generated')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('resource_type', models.CharField(help_text='e.g., Patient, Consultation, Invoice', max_length=50)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('resource_repr', models.CharField(blank=True, help_text='Human-readable identifier', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('previous_state', models.JSONField(blank=True, default=dict)),
                ('new_state', models.JSONField(blank=True, default=dict)),
                ('change_summary', models.TextField(blank=True)),
                ('pdpa_compliant', models.BooleanField(default=True)),
                ('consent_verified', models.BooleanField(default=False)),
                ('retention_until', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action', 'created_at'], name='audit_log_user_id_7b1d88_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_log_resourc_2570dd_idx'), models.Index(fields=['severity', 'created_at'], name='audit_log_severit_e9b3e7_idx'), models.Index(fields=['ip_address', 'created_at'], name='audit_log_ip_addr_f5a3a9_idx'), models.Index(fields=['pdpa_compliant', 'created_at'], name='audit_log_pdpa_co_7cee1e_idx')],
            },
        ),
    ]
